In [1]:
#The trade sell and bid for a pair of defined pair

import matplotlib as plt
import numpy as np
import pandas as pd

In [3]:
filename="stock_data.csv"
df=pd.read_csv(filename)
df.head()

         Date    Stock    Open    High     Low   Close   Volume
0  2023-01-01  STOCK_A  100.00  100.43   96.51   97.94  1957770
1  2023-01-01  STOCK_B   50.00   50.26   47.73   48.58  1080000
2  2023-01-01  STOCK_C  200.00  202.03  193.58  196.05  1571546
3  2023-01-02  STOCK_A   97.94   99.24   94.08   95.39  1897865
4  2023-01-02  STOCK_B   48.58   48.84   47.63   48.03   507676

In [ ]:
related=["STOCK_A","STOCK_B"]

rel_a=df[df["Stock"]==related[0]].sort_values("Date").copy()
rel_b=df[df["Stock"]==related[1]].sort_values("Date").copy()

#reindex

            Date    Stock    Open    High    Low  Close   Volume
0     2023-01-01  STOCK_A  100.00  100.43  96.51  97.94  1957770
3     2023-01-02  STOCK_A   97.94   99.24  94.08  95.39  1897865
6     2023-01-03  STOCK_A   95.39   97.98  94.21  97.86   623799
9     2023-01-04  STOCK_A   97.86   97.90  95.50  97.23  1263759
12    2023-01-05  STOCK_A   97.23   99.16  95.68  96.12  1229044
...          ...      ...     ...     ...    ...    ...      ...
1080  2023-12-27  STOCK_A   61.84   62.34  60.25  60.82   552527
1083  2023-12-28  STOCK_A   60.82   61.18  58.53  59.28  1357965
1086  2023-12-29  STOCK_A   59.28   59.75  58.99  59.27  1499428
1089  2023-12-30  STOCK_A   59.27   60.05  58.77  58.83   805609
1092  2023-12-31  STOCK_A   58.83   59.84  57.84  59.20  1591069

[365 rows x 7 columns]

In [10]:
#We assume that they have passed the cointegration test and they relates

hist_diff=rel_a['Close']-rel_b['Close']
diff_mean=hist_diff.mean()
diff_sd=hist_diff.std()

In [ ]:
##if the prices far enough away, buy low sell high, when close enough sellout
#connect to rotman

a_now=0
b_now=10
a_cnt=0
b_cnt=0
#rolling sd?
#crossing moving average in reverse as exit
if a_now-b_now>2*diff_sd:
    buy b
    sell a

if b_now-a_now>2*diff_sd:
    buy a
    sell b

if abs(a_now-b_now)<diff_sd:
    buy a_cnt
    buy b_cnt